version: "3.7"

services:

  postgres:
    image: postgres:14-alpine
    container_name: postgres-idiario
    # command: executar manualmente dentro do container postgres-idiario os comandos do arquivo ./script/restore-backup
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../backup:/backup
      - ./script:/script
    environment:
      - POSTGRES_DB=idiario_development
      - POSTGRES_USER=idiario
      - POSTGRES_PASSWORD=idiario

  redis:
    image: redis:alpine
    container_name: redis-idiario
    ports:
      - 6379

  app:
    build: .
    container_name: idiario
    command: ./script/start
    volumes:
      - .:/app
      - box:/box
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=idiario
      - DATABASE_PASSWORD=idiario
      - REDIS_URL=redis://redis:6379/0
      - SUPPORT_NUMBER=82981670619
    depends_on:
      - postgres
      - redis

  sidekiq:
    build: .
    container_name: idiario-sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml -e development
    volumes:
      - .:/app
      - box:/box
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=idiario
      - DATABASE_PASSWORD=idiario
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
  

volumes:
  app:
  box:
  pg_data:
