:concurrency: 5

staging:
  :concurrency: 10

production:
  :concurrency: 10

:queues:
  - [default, 1]
  - [critical, 2]
  - [low, 1]
  - [exam_posting, 2]
  - [exam_posting_1, 1]
  - [exam_posting_2, 1]
  - [synchronizer, 3]
  - [synchronizer_enqueue_next_job, 3]

:timeout: 1200
