---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
:queues:
  - [default, 1]
  - [low, 1]
  - [exam_posting, 2]
  - [synchronizer, 1]
