#!/bin/bash

bundle check || BUNDLE_JOBS=4 bundle install

yarn install

if ! test -f ".setup"; then
  echo -e "
  development:
    secret_key_base: `bundle exec rake secret`
    REDIS_URL: redis://redis:6379/0
    shortcuts_enabled: true
    only_one_conceptual_avaliation: false
    show_objectives: true
    SEMESTRAL_RECOVERY: true
    " > config/secrets.yml

  cp config/database.sample.yml config/database.yml

  RAILS_ENV=development bundle exec rake db:create
  RAILS_ENV=development bundle exec rake db:migrate
  bundle exec rake entity:setup NAME=docker DOMAIN=localhost DATABASE=idiario
  # executar esse comando somente se banco de dados for novo
  bundle exec rake entity:admin:create NAME=docker ADMIN_PASSWORD=A123456789$

  cp public/404.html.sample public/404.html
  cp public/500.html.sample public/500.html

  touch .setup
fi

rm -f /app/tmp/pids/server.pid

echo "Starting.."
bundle exec rails server -b 0.0.0.0 -e development

sleep 30
